---
title: "Model fitting 02_03_20"
author: "Heather Welch"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('/Users/heatherwelch/Dropbox/melenoma/melanoma_GitHub/utilities/load_libraries.R')
# library(gam)
library(mgcv)
library(lme4)
library(MuMIn)
library(scales)
modDF=read.csv("/Users/heatherwelch/Dropbox/melenoma/melanoma_GitHub/model_data/data_01_30_20_withpop_FIPS_STATEFP.csv")

```

## Mixed medical best
 
```{r}
summary(lmer(SEER_rate~rescale(incm_mh,to=c(0,100))+rescale(wpovr50,to=c(0,100))+(1|STATEFP),data=modDF))
```

## Linear medical best
 
```{r}
summary(lm(SEER_rate~rescale(incm_mh,to=c(0,100))+rescale(wpovr50,to=c(0,100)),data=modDF))
```
 
## Mixed medical ALL
 
```{r}
summary(lmer(SEER_rate~rescale(incm_mh,to=c(0,100))+rescale(wpovr50,to=c(0,100))+rescale(wpvr100,to=c(0,100))+rescale(docs_pk,to=c(0,100))+rescale(pcp_pk,to=c(0,100))+rescale(derm_pk,to=c(0,100))+(1|STATEFP),data=modDF))
```

## Linear medical ALL
 
```{r}
summary(lm(SEER_rate~rescale(incm_mh,to=c(0,100))+rescale(wpovr50,to=c(0,100))+rescale(wpvr100,to=c(0,100))+rescale(docs_pk,to=c(0,100))+rescale(pcp_pk,to=c(0,100))+rescale(derm_pk,to=c(0,100)),data=modDF))
```
 
## Mixed environment best
 
```{r}
summary(lmer(SEER_rate~rescale(UV_irradiance,to=c(0,100))+rescale(seasonality_temperature,to=c(0,100))+(1|STATEFP),data=modDF))
```

## Linear environment best
 
```{r}
summary(lm(SEER_rate~rescale(UV_irradiance,to=c(0,100))+rescale(seasonality_temperature,to=c(0,100)),data=modDF))
```
 
## Mixed environment ALL
 
```{r}
summary(lmer(SEER_rate~rescale(UV_irradiance,to=c(0,100))+rescale(seasonality_temperature,to=c(0,100))+rescale(sun_exposure,to=c(0,100))+rescale(seasonality_cloud,to=c(0,100))+rescale(elevation,to=c(0,100))+rescale(mean_cloud,to=c(0,100))+(1|STATEFP),data=modDF))
```

## Linear environment ALL
 
```{r}
summary(lm(SEER_rate~rescale(UV_irradiance,to=c(0,100))+rescale(seasonality_temperature,to=c(0,100))+rescale(sun_exposure,to=c(0,100))+rescale(seasonality_cloud,to=c(0,100))+rescale(elevation,to=c(0,100))+rescale(mean_cloud,to=c(0,100)),data=modDF))
```
 
 
