# load libraries
library(raster)
library(data.table)
library(tidyverse)
library(gdata)
library(plotly)
library(glue)
library(parallel)
library(lubridate)
library(rgeos)
library(mgcv)
library(lme4)
library(MuMIn)
library(shinydashboard)
library(highcharter)
library(rlang)
